import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
      </head>
      <body
        className={`layoutWrapper ${geistSans.variable} ${geistMono.variable}`}
      >
        <div className="pageWrapper"
          
        style={{ display: "flex", flexDirection: "column", minHeight: "100vh" }}>
  <Navbar />
  <main style={{ flex: 1 }}>{children}</main>
  <Footer />
</div>

      </body>
    </html>
  );
}

